import type { Metadata } from "next";
import 'bootstrap-icons/font/bootstrap-icons.css';
import 'bootstrap/dist/css/bootstrap.css';
import 'aos/dist/aos.css';
import "./variables.css";
import "./globals.css";
import { GoogleTagManager } from '@next/third-parties/google' 



export const metadata: Metadata = {
  title: "Cook it Easy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GoogleTagManager gtmId="GTM-WBT745PF" />
      <body>
      <noscript>
        <iframe 
        src="https://www.googletagmanager.com/ns.html?id=GTM-WBT745PF"
        height="0"
        width="0"
        style={{ display: "none", visibility: "hidden" }}>
        </iframe>
      </noscript>
        {children}</body>
    </html>
  );
}
