import type { Metadata } from "next";
import {EB_Garamond} from "next/font/google";
import 'bootstrap-icons/font/bootstrap-icons.css';
import 'bootstrap/dist/css/bootstrap.css';
import 'aos/dist/aos.css'
import "./variables.css";
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import Head from "next/head";


const ebGaramond = EB_Garamond({subsets: ['latin']});

export const metadata: Metadata = {
  title: "Cook it Easy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <body className={ebGaramond.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
