import type { Metadata } from "next";
import {EB_Garamond} from "next/font/google";
import 'bootstrap-icons/font/bootstrap-icons.css';
import 'bootstrap/dist/css/bootstrap.css';
import 'aos/dist/aos.css'
import "./variables.css";
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import Head from "next/head";
import Script from "next/script";


const ebGaramond = EB_Garamond({subsets: ['latin']});

export const metadata: Metadata = {
  title: "Cook it Easy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <script
      async
      src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${process.env.NEXT_PUBLIC_ADSENSE_PID}`}
      crossOrigin="anonymous"
      ></script>
      <meta name="google-adsense-account" content={process.env.NEXT_PUBLIC_ADSENSE_PID}></meta>

      <Head>
        <link rel="icon" href="/favicon.ico"/>    
        
      </Head>
      <body className={ebGaramond.className}>
        <Header/>
        {children}
        <Footer/>
        
      </body>
    </html>
  );
}
